services:

  postgres:
    image: postgres:17
    container_name: postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=server_db
      - TZ=Asia/Dubai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d server_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  datacollection:
    container_name: DataCollection
    build: ./srcs/DataCollection
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TZ=Asia/Dubai
    volumes:
      - ./srcs/DataCollection:/app
    networks:
      - backend
    depends_on:
      - postgres
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "datacollection"

  dashboard:
    container_name: Dashboard
    build: ./srcs/Backend
    restart: unless-stopped
    ports:
      - "80:5000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Dubai
    volumes:
      - ./srcs/Backend:/app
    networks:
      - backend
    depends_on:
      - postgres
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "dashboard"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
    driver: local
